[env]
OPENSSL_DIR  = { value = "D:/Develop/android_openssl/ssl_3", relative = false }
AARCH64_LINUX_ANDROID_OPENSSL_LIB_DIR = { value = "D:/Develop/android_openssl/ssl_3/arm64-v8a", relative = false }
CC = { value = "C:/Users/24071/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android21-clang" }
AR = { value = "C:/Users/24071/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar" }
RUST_BACKTRACE= { value = "full" }