name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v4
      with: 
        repository: KDAB/android_openssl
        path: ssl
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
    - name: check ndk
      run: cd $ANDROID_NDK_HOME && pwd
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.34'
    - name: PreBuild
      run: rustup target add aarch64-linux-android
    - name: Build
      run: cd rust && cargo b --target aarch64-linux-android --release
